export default { //34个省、市、自治区的名字拼音映射数组 space: 40 需要预留的间隔，才不会超出容器, size: 地图 宽/高 是否大于1
    "全国": { name: '中国', file: "chain", center: ['50%', '50%'], space: -100, size: false },
    //23个省
    "台湾": { name: '台湾省', file: "taiwan", center: ['50%', '50%'], space: 60, size: false },
    "河北": { name: '河北省', file: "hebei", center: ['50%', '50%'], space: 60, size: false },
    "山西": { name: '山西省', file: "shangxi", center: ['50%', '50%'], space: 60, size: false },
    "辽宁": { name: '辽宁省', file: "liaoning", center: ['50%', '50%'], space: 40, size: false },
    "吉林": { name: '吉林省', file: "jilin", center: ['50%', '50%'], space: 60, size: true },
    "黑龙江": { name: '黑龙江省', file: "heilongjiang", center: ['50%', '50%'], space: 60, size: false },
    "江苏": { name: '江苏省', file: "jiangsu", center: ['50%', '50%'], space: 60, size: false },
    "浙江": { name: '浙江省', file: "zhejiang", center: ['50%', '50%'], space: 80, size: false },
    "安徽": { name: '安徽省', file: "anhui", center: ['50%', '50%'], space: 60, size: false },
    "福建": { name: '福建省', file: "fujian", center: ['50%', '50%'], space: 60, size: false },
    "江西": { name: '江西省', file: "jiangxi", center: ['50%', '50%'], space: 60, size: false },
    "山东": { name: '山东省', file: "shangdong", center: ['50%', '50%'], space: 80, size: true },
    "河南": { name: '河南省', file: "henan", center: ['50%', '50%'], space: 80, size: false },
    "湖北": { name: '湖北省', file: "hubei", center: ['50%', '50%'], space: 60, size: true },
    "湖南": { name: '湖南省', file: "hunan", center: ['50%', '50%'], space: 60, size: false },
    "广东": { name: '广东省', file: "guangdong", center: ['50%', '50%'], space: 60, size: false },
    "海南": { name: '海南省', file: "hainan", center: ['50%', '50%'], space: 260, size: true },
    "四川": { name: '四川省', file: "sichuan", center: ['50%', '50%'], space: 60, size: false },
    "贵州": { name: '贵州省', file: "guizhou", center: ['50%', '50%'], space: 100, size: false },
    "云南": { name: '云南省', file: "yunnan", center: ['50%', '50%'], space: 60, size: false },
    "陕西": { name: '陕西省', file: "shanxi", center: ['50%', '50%'], space: 60, size: false },
    "甘肃": { name: '甘肃省', file: "gansu", center: ['50%', '50%'], space: -60, size: false },
    "青海": { name: '青海省', file: "qinghai", center: ['49%', '50%'], space: 80, size: true },
    //5个自治区
    "新疆": { name: '新疆维吾尔自治区', file: "xinjiang", center: ['50%', '50%'], space: -40, size: false },
    "广西": { name: '广西壮族自治区', file: "guangxi", center: ['50%', '50%'], space: 40, size: false },
    "内蒙古": { name: '内蒙古自治区', file: "neimenggu", center: ['50%', '50%'], space: 60, size: true },
    "宁夏": { name: '宁夏回族自治区', file: "ningxia", center: ['50%', '50%'], space: 60, size: false },
    "西藏": { name: '西藏自治区', file: "xizang", center: ['50%', '50%'], space: 60, size: true },
    //4个直辖市
    "北京": { name: '北京市', file: "beijing", center: ['50%', '50%'], space: 60, size: false },
    "天津": { name: '天津市', file: "tianjin", center: ['50%', '50%'], space: 60, size: false },
    "上海": { name: '上海市', file: "shanghai", center: ['50%', '50%'], space: 60, size: false },
    "重庆": { name: '重庆市', file: "chongqing", center: ['50%', '50%'], space: 60, size: false },
    //2个特别行政区
    "香港": { name: '香港特別行政區', file: "xianggang", center: ['50%', '50%'], space: 40, size: false },
    "澳门": { name: '澳门特别行政区', file: "aomen", center: ['50%', '50%'], space: 40, size: true },
}